export const copy = {
  brand: "오피스톤",
  headline: "할 말은 그대로,\n톤만 다듬어요.",
  sub: "보내기 어려운 회사 메시지가 있나요?\n속마음 그대로 적어주세요.",
  support: "얼마나 부드럽게 말할지, 얼마나 선을 그을지는 직접 정할 수 있어요.",
  placeholder: "아니 애초에 기획이 바뀐 건데 제가 왜 오늘 야근해서 맞춰야 하죠?",
  privacy: "회사 기밀이나 개인정보는 넣지 말아주세요. 입력한 내용은 오피스톤에 저장하지 않아요.",
  temperature: "말의 온도를 맞춰볼까요?",
  directness: "얼마나 직접적으로 말할까요?",
  defensiveness: "선을 어느 정도까지 그을까요?",
  business: "회사 말투는 얼마나 넣을까요?",
  directnessLow: "부드럽게",
  directnessHigh: "직진하게",
  defensivenessLow: "유연하게",
  defensivenessHigh: "선을 명확히",
  businessLow: "편하게",
  businessHigh: "공식적으로",
  cta: "보내기 좋게 바꿔주세요",
  loading: "톤을 맞추고 있어요...",
  resultTitle: "이 정도면 보내도 괜찮아요.",
  copy: "복사하기",
  copied: "복사했어요",
  retry: "다시 다듬기",
  preservedTitle: "오피스톤이 남겨둔 내용",
  error: "톤을 다듬지 못했어요. 잠시 후 다시 한번 해주세요.",
  empty: "하고 싶은 말을 그대로 적어주세요.",
  intentHint: "선택하면 의도를 조금 더 분명하게 전달해요. 안 골라도 괜찮아요.",
};
