export const copy = {
  brand: "오피스톤",
  headline: "할 말은 해야 하는데,\n회사라서 고민될 때.",
  sub: "속마음은 그대로 적으세요.\n보내기 좋은 말투만 맞춰드릴게요.",
  support: "먼저 느낌을 고르고, 필요할 때만 세부 온도를 조절하세요.",
  rawReplyLabel: "나는 뭐라고 답하고 싶나요?",
  rawReplyHint: "욕이 섞여도 괜찮아요. 핵심 입장은 지키고 표현만 다듬어요.",
  placeholderRawReply: "아니 이거 제가 만든 것도 아닌데 왜 제가 내일까지 보고서를 써야 하죠?",
  contextToggle: "상대가 한 말도 있어요",
  contextLabel: "상대가 뭐라고 했나요?",
  contextHint: "받은 메시지나 상황이에요. 이 문장을 고치는 게 아니라 답변의 근거로만 써요.",
  placeholderContext: "DB 컬럼 미스 건 내일까지 보고 작성하세요.",
  privacy: "회사 기밀이나 개인정보는 넣지 말아주세요. 입력한 내용은 오피스톤에 저장하지 않아요.",
  temperature: "어떻게 말할까요?",
  advanced: "세부 톤 직접 조절하기",
  directness: "직진도",
  defensiveness: "선 긋기",
  business: "회사 말투",
  directnessLow: "돌려서",
  directnessHigh: "결론부터",
  defensivenessLow: "함께 풀기",
  defensivenessHigh: "책임 명확히",
  businessLow: "메신저처럼",
  businessHigh: "공식적으로",
  cta: "답변 만들기",
  loading: "말투를 맞추고 있어요...",
  resultTitle: "이렇게 보내는 걸 추천해요.",
  resultHint: "같은 입장을 유지한 다른 표현이에요.",
  copy: "복사하기",
  copied: "복사했어요",
  retry: "다시 만들기",
  preservedTitle: "이 내용은 그대로 남겼어요",
  error: "톤을 다듬지 못했어요. 잠시 후 다시 한번 해주세요.",
  empty: "뭐라고 답하고 싶은지 적어주세요.",
  detected: "오피스톤이 이렇게 읽었어요",
  share: "공유 카드",
};
