export const copy = {
  brand: "오피스톤",
  headline: "할 말은 그대로,\n톤만 다듬어요.",
  sub: "보내기 어려운 회사 메시지가 있나요?\n속마음 그대로 적어주세요.",
  support: "직진도, 선, 회사 말투만 맞추면 돼요.",
  rawReplyLabel: "뭐라고 답하고 싶나요?",
  rawReplyHint: "속마음 그대로 적어도 괜찮아요.",
  placeholderRawReply: "아니 이거 제가 만든 것도 아닌데\n왜 제가 내일까지 보고서를 써야 하죠?",
  contextToggle: "상대가 한 말이나 상황도 알려줄게요",
  contextLabel: "상대가 뭐라고 했나요?",
  contextHint: "받은 메시지나 상황을 알려주면 더 정확하게 다듬을 수 있어요.",
  placeholderContext: "DB 컬럼 미스 건 내일까지 보고 작성하세요.",
  privacy: "회사 기밀이나 개인정보는 넣지 말아주세요. 입력한 내용은 오피스톤에 저장하지 않아요.",
  temperature: "말의 온도를 맞춰볼까요?",
  directness: "얼마나 직접적으로 말할까요?",
  defensiveness: "선을 어디까지 그을까요?",
  business: "회사 말투는 얼마나 넣을까요?",
  directnessLow: "부드럽게",
  directnessHigh: "직진하게",
  defensivenessLow: "유연하게",
  defensivenessHigh: "선을 명확히",
  businessLow: "편하게",
  businessHigh: "공식적으로",
  cta: "보내기 좋게 바꿔주세요",
  loading: "톤을 맞추고 있어요...",
  resultTitle: "이렇게 말해보세요.",
  resultHint: "같은 온도로 문장만 다르게 적어둔 후보예요.",
  copy: "복사하기",
  copied: "복사했어요",
  retry: "다시 다듬기",
  preservedTitle: "이 내용은 그대로 남겼어요",
  error: "톤을 다듬지 못했어요. 잠시 후 다시 한번 해주세요.",
  empty: "뭐라고 답하고 싶은지 적어주세요.",
  intentHint: "선택하면 의도를 조금 더 분명하게 전달해요. 안 골라도 괜찮아요.",
};
